/**
 * ============================================================================
 * JV GOLD — JESSE'S REAL BOOK, IMPORTED
 * ============================================================================
 *
 * GENERATED FILE. Do not hand-edit.
 *   Regenerate:  node scripts/import-sessions.mjs
 *   Source:      SESSION TRACK JVGOLD PRIVATE TRAINING.xlsm (one tab per client)
 *   Importer:    scripts/import-sessions.mjs
 *   Vocabulary:  ~/lib/ops/vocabulary
 *
 * ---------------------------------------------------------------------------
 * PRIVACY — READ BEFORE IMPORTING THIS MODULE
 * ---------------------------------------------------------------------------
 * These are REAL clients of Jesse's, and several of them are MINORS. This file
 * is for authenticated hub routes only, behind row-level security. Nothing in
 * it may reach a public route, a <meta> tag, an OG image, a sitemap, a log line
 * or an analytics payload. It is the opposite of `~/lib/ops/seed`, which is
 * de-identified precisely so it can be shown to anyone.
 *
 * ---------------------------------------------------------------------------
 * WHAT THE BOOK DOES NOT CONTAIN
 * ---------------------------------------------------------------------------
 * His workbook has no column for competitive level, date of birth, email,
 * school, waiver status, session focus, or the value of an unpaid session.
 * Those import as `null` / `''` / `false`, never as a guess. Two domain
 * fields had to be widened to say so honestly, which is why this file exports
 * `HistoryClient` and `HistorySession` rather than `Client` and
 * `TrainingSession`:
 *
 *   - `HistoryClient.level`        `ClientLevel | null`  (never recorded)
 *   - `HistorySession.kind`        `SessionKind | null`  (blank Training Type)
 *   - `HistorySession.amountCents` `number | null`       (unpriced ≠ free)
 *
 * Use `toTrainingSession()` at the point where a component genuinely needs the
 * strict type; it makes you name the fallback out loud.
 *
 * ---------------------------------------------------------------------------
 * BLANK IS NOT ZERO
 * ---------------------------------------------------------------------------
 * `-` and empty cells import as `null`. A session with `amountCents: null`
 * is one he never priced. A session with `amountCents: 0` would be one he
 * comped. Do not `?? 0` these on the way into a total without saying so in the
 * caption.
 *
 * ---------------------------------------------------------------------------
 * HIS NUMBERS DO NOT ALL AGREE
 * ---------------------------------------------------------------------------
 * See `HISTORY_RECONCILIATION`. His May Dashboard, his income-by-stream rows
 * and his session log disagree with each other. Nothing here picks a winner —
 * every figure is carried with its source so a screen can show both and label
 * the gap.
 */

import type {
  ClientLevel,
  Client,
  IsoDate,
  Payment,
  PaymentCategory,
  SessionKind,
  SessionId,
  TrainingSession,
} from './types';
import type {
  IncomeStreamId,
  PackageTypeId,
  PaymentMethodId,
  ResolutionMatch,
  TrainingTypeId,
} from './vocabulary';

/* ==========================================================================
 * TYPES
 * ======================================================================== */

/**
 * A `Client` as his book can actually support it, plus the provenance needed
 * to trace any figure back to a tab.
 */
export interface HistoryClient extends Omit<Client, 'level'> {
  /** `null` — his book has no competitive-level column. Never guessed. */
  level: ClientLevel | null;
  /** The workbook tab this came from, verbatim. */
  sourceSheet: string;
  /** His exact spelling/casing of the name, before display title-casing. */
  sourceName: string;
  packageTypeId: PackageTypeId | null;
  /**
   * His "Family" column, verbatim — which records CLUB affiliation
   * ("Deep Waters RTC", 'Norco / Future Champions "CHAMP CLUB"'), not a billing
   * household. `familyGroup` is therefore `null` for everyone: nothing in the
   * book says which athletes share a bill. Do not infer it from surnames.
   */
  clubAffiliationRaw: string | null;
  /** Rows on this tab, including unlogged ones. */
  sessionCount: number;
  /** Rows carrying real evidence (a note, a payment, a type, or a used count). */
  loggedSessionCount: number;
  paymentCount: number;
}

/** A `TrainingSession` with the two fields his book leaves unknowable. */
export interface HistorySession
  extends Omit<TrainingSession, 'kind' | 'amountCents'> {
  /** `null` when the Training Type cell was blank. Not a default. */
  kind: SessionKind | null;
  /** What he COLLECTED on this row, in cents. `null` = never priced. */
  amountCents: number | null;
}

/** Where a session's duration came from. */
export type DurationSource =
  | 'note-range'
  | 'training-type-default'
  | 'fallback-60';

/** Everything the domain types have no room for. Keyed by session id. */
export interface HistorySessionMeta {
  sourceSheet: string;
  /** 0-based index in the extracted row list. Stable across re-imports. */
  sourceRow: number;
  clientId: string;
  packageTypeId: PackageTypeId | null;
  /** His cell contents, verbatim. */
  rawPackageType: string;
  packageMatch: ResolutionMatch;
  trainingTypeId: TrainingTypeId | null;
  rawTrainingType: string;
  trainingMatch: ResolutionMatch;
  paymentMethodId: PaymentMethodId | null;
  rawPaymentMethod: string;
  paymentMatch: ResolutionMatch;
  paidCents: number | null;
  /** His Owed column. `null` = blank, `0` = he typed a zero. */
  owedCents: number | null;
  /** His "Sessions Used" cell: `1`, `0`, or `null` for blank. */
  sessionsUsedRaw: number | null;
  /**
   * `false` when no clock could be read out of his note. The session's
   * `start` is then `T00:00:00` — render "time not recorded", NOT "12:00 AM".
   */
  startTimeRecorded: boolean;
  durationSource: DurationSource;
  /** `'note-keyword'` when the location was recognised in his note. */
  locationSource: 'note-keyword' | null;
  /** `false` for a pre-filled date row with nothing on it. */
  logged: boolean;
  clubAffiliationRaw: string;
}

export interface HistoryDateRange {
  first: IsoDate;
  last: IsoDate;
}

/** One row of his Dashboard's income-by-stream table. */
export interface DashboardStreamFigure {
  incomeStreamId: IncomeStreamId;
  cents: number;
}

/** His May Dashboard, transcribed. NOT derived from the session rows. */
export interface DashboardMonth {
  month: string;
  incomeCents: number;
  expensesCents: number;
  netCents: number;
  outstandingCents: number;
  activeClients: number;
  coachPayCents: number;
  byStream: DashboardStreamFigure[];
}

/** One disagreement between the imported book and his own reporting. */
export interface ReconciliationLine {
  id: string;
  label: string;
  /** Cents derived from the imported rows. `null` when not a money line. */
  importedCents: number | null;
  /** Cents as his Dashboard states them. `null` when not a money line. */
  dashboardCents: number | null;
  deltaCents: number | null;
  note: string;
  /** `true` only when the two sides actually agree. */
  resolved: boolean;
}

export interface VocabularyAlias {
  vocabulary: string;
  /** His string, verbatim. */
  raw: string;
  canonicalId: string;
  canonicalLabel: string;
  match: ResolutionMatch;
}

export interface SkippedRow {
  sourceRow: number;
  sheet: string;
  reason: string;
}

export interface UnmappedValue {
  sourceRow: number;
  sheet: string;
  vocabulary: string;
  raw: string;
}

export interface ImportFlag {
  code: string;
  severity: 'info' | 'warning' | 'error';
  message: string;
}

export interface ImportReport {
  sourceRowCount: number;
  importedRowCount: number;
  clientCount: number;
  paymentCount: number;
  paymentTotalCents: number;
  paymentTotalByMonth: Record<string, number>;
  outstandingCents: number;
  dateRange: HistoryDateRange;
  perClient: {
    clientId: string;
    name: string;
    sessions: number;
    logged: number;
    payments: number;
    paidCents: number;
    owedCents: number;
  }[];
  /** Template tabs and unusable rows. Nothing real is in here. */
  skipped: SkippedRow[];
  /** Every drifted string that was folded onto a canonical id. */
  aliased: VocabularyAlias[];
  /** Canonical entries added because his Lists sheet had no home for a value. */
  invented: {vocabulary: string; id: string; label: string; reason: string}[];
  /** Real values nobody has mapped. Empty is the goal; non-empty needs a human. */
  unmapped: UnmappedValue[];
  flags: ImportFlag[];
}

/* ==========================================================================
 * DATA
 * ======================================================================== */

/**
 * The date this dataset is anchored to: the LAST session in his book, not
 * today. Any "days since" figure must be computed against this, so the hub
 * renders identically on the server and in the browser.
 */
export const HISTORY_ANCHOR_DATE: IsoDate = '2026-07-05';


/** First and last dated row in the book. */
export const HISTORY_DATE_RANGE: HistoryDateRange = {
  first: '2026-05-11',
  last: '2026-07-05',
};


/**
 * His six real clients, sorted by id. `status` is DERIVED, not recorded: a
 * client with a positive Owed balance is 'Owes Balance', everyone else is
 * 'Active'. Nobody is marked 'Inactive' or 'Trial' — his book does not say so
 * and a lapsed athlete is not something to infer.
 */
export const HISTORY_CLIENTS: readonly HistoryClient[] = [
  {
    id: 'callum-barkenhagen',
    name: 'Callum Barkenhagen',
    accountLabel: 'Callum Barkenhagen',
    guardian: 'Aaron Barkenhagen',
    email: null,
    phone: '951-741-2650',
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Active',
    familyGroup: null,
    packages: {
      name: 'Other',
      priceCents: null,
      purchased: null,
      used: 1,
      remaining: null,
      offeringId: null,
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: 'Aaron Barkenhagen',
      emergencyContactPhone: '951-741-2650',
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-05-19',
    lastSessionAt: '2026-05-19',
    lifetimeValueCents: 100000,
    balanceCents: 0,
    source: 'import',
    rateCents: null,
    colorIndex: 0,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'Callum Barkenhagen',
    sourceName: 'Callum Barkenhagen',
    packageTypeId: 'other',
    clubAffiliationRaw: 'Norco / Future Champions "CHAMP CLUB"',
    sessionCount: 1,
    loggedSessionCount: 1,
    paymentCount: 1,
  },
  {
    id: 'gage-kotaro',
    name: 'Gage Kotaro',
    accountLabel: 'Gage Kotaro',
    guardian: null,
    email: null,
    phone: null,
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Active',
    familyGroup: null,
    packages: {
      name: 'Single Session',
      priceCents: null,
      purchased: null,
      used: 1,
      remaining: null,
      offeringId: 'private',
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: null,
      emergencyContactPhone: null,
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-06-01',
    lastSessionAt: '2026-06-01',
    lifetimeValueCents: 0,
    balanceCents: 0,
    source: 'import',
    rateCents: null,
    colorIndex: 1,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'GAGE KOTARO',
    sourceName: 'GAGE KOTARO',
    packageTypeId: 'single-session',
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
    sessionCount: 1,
    loggedSessionCount: 1,
    paymentCount: 0,
  },
  {
    id: 'kade-kean',
    name: 'Kade Kean',
    accountLabel: 'Kade Kean',
    guardian: 'Nick Kean',
    email: null,
    phone: '951-313-5733',
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Owes Balance',
    familyGroup: null,
    packages: {
      name: 'Single Session',
      priceCents: null,
      purchased: null,
      used: 3,
      remaining: null,
      offeringId: 'private',
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: 'Nick Kean',
      emergencyContactPhone: '951-313-5733',
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-05-21',
    lastSessionAt: '2026-05-27',
    lifetimeValueCents: 90000,
    balanceCents: 40000,
    source: 'import',
    rateCents: null,
    colorIndex: 2,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'Kade Kean',
    sourceName: 'Kade Kean',
    packageTypeId: 'single-session',
    clubAffiliationRaw: 'Deep Waters RTC',
    sessionCount: 5,
    loggedSessionCount: 5,
    paymentCount: 5,
  },
  {
    id: 'levi-prado',
    name: 'Levi Prado',
    accountLabel: 'Levi Prado',
    guardian: 'JEREMY PRADO',
    email: null,
    phone: '951-204-7419',
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Active',
    familyGroup: null,
    packages: {
      name: '20-Session Package',
      priceCents: null,
      purchased: 20,
      used: 1,
      remaining: 19,
      offeringId: 'package',
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: 'JEREMY PRADO',
      emergencyContactPhone: '951-204-7419',
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-06-01',
    lastSessionAt: '2026-06-01',
    lifetimeValueCents: 0,
    balanceCents: 0,
    source: 'import',
    rateCents: null,
    colorIndex: 3,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'LEVI PRADO',
    sourceName: 'LEVI PRADO',
    packageTypeId: '20-session-package',
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
    sessionCount: 1,
    loggedSessionCount: 1,
    paymentCount: 0,
  },
  {
    id: 'paulie-varela',
    name: 'Paulie Varela',
    accountLabel: 'Paulie Varela',
    guardian: 'PAUL VARELA',
    email: null,
    phone: '909-224-5934',
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Active',
    familyGroup: null,
    packages: {
      name: '20-Session Package',
      priceCents: null,
      purchased: 20,
      used: 20,
      remaining: 0,
      offeringId: 'package',
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: 'PAUL VARELA',
      emergencyContactPhone: '909-224-5934',
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-05-11',
    lastSessionAt: '2026-06-14',
    lifetimeValueCents: 300000,
    balanceCents: 0,
    source: 'import',
    rateCents: null,
    colorIndex: 4,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'PAULIE VARELA',
    sourceName: 'PAULIE VARELA',
    packageTypeId: '20-session-package',
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
    sessionCount: 20,
    loggedSessionCount: 20,
    paymentCount: 1,
  },
  {
    id: 'rosie-varela',
    name: 'Rosie Varela',
    accountLabel: 'Rosie Varela',
    guardian: null,
    email: null,
    phone: null,
    level: null,
    school: null,
    dateOfBirth: null,
    status: 'Active',
    familyGroup: null,
    packages: {
      name: 'Single Session',
      priceCents: null,
      purchased: null,
      used: 8,
      remaining: null,
      offeringId: 'private',
    },
    compliance: {
      usawCardNumber: null,
      hasHealthInsurance: null,
      insuranceProvider: null,
      insurancePolicyNumber: null,
      emergencyContactName: null,
      emergencyContactPhone: null,
      waiverSigned: false,
    },
    tags: [],
    joinedAt: '2026-06-17',
    lastSessionAt: '2026-07-05',
    lifetimeValueCents: 300000,
    balanceCents: 0,
    source: 'import',
    rateCents: null,
    colorIndex: 5,
    notes: null,
    shopifyCustomerId: null,
    sourceSheet: 'Rosie Varela',
    sourceName: 'Rosie Varela',
    packageTypeId: 'single-session',
    clubAffiliationRaw: 'Deep Waters RTC',
    sessionCount: 13,
    loggedSessionCount: 8,
    paymentCount: 1,
  },
];


/**
 * Every dated row, sorted by start then id. `status` is 'completed' when the
 * row carries evidence (a note, a payment, a training type, or a used count)
 * and 'scheduled' when he pre-filled a date and nothing else. `focus` is
 * always `''` — his book has one free-text Notes column and it is preserved
 * verbatim in `notes`.
 */
export const HISTORY_SESSIONS: readonly HistorySession[] = [
  {
    id: 's-paulie-varela-2026-05-11-01',
    start: '2026-05-11T05:00:00',
    end: '2026-05-11T06:30:00',
    minutes: 90,
    kind: 'workout',
    offeringId: 'workout',
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: 300000,
    paid: true,
    paidDate: '2026-05-11',
    method: 'Cash',
    notes: '1st session- @ HOME 5AM LIFT',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-05-16-01',
    start: '2026-05-16T00:00:00',
    end: '2026-05-16T04:00:00',
    minutes: 240,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Great Oak HS',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'GREAT OAK IEWA TOURNAMENT - COACHING PAULIE & ZACH',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-05-17-01',
    start: '2026-05-17T00:00:00',
    end: '2026-05-17T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'JW North HS',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'JW NORTH IEWA TOURNAMENT - ROSIE , ZACH, ISAAC, PAULIE,',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-callum-barkenhagen-2026-05-19-01',
    start: '2026-05-19T00:00:00',
    end: '2026-05-19T01:00:00',
    minutes: 60,
    kind: 'partner',
    offeringId: 'partner',
    athleteIds: ['callum-barkenhagen'],
    location: '',
    focus: '',
    amountCents: 100000,
    paid: true,
    paidDate: '2026-05-19',
    method: 'Zelle',
    notes: '1st session',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-kade-kean-2026-05-21-01',
    start: '2026-05-21T00:00:00',
    end: '2026-05-21T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['kade-kean'],
    location: '',
    focus: '',
    amountCents: 20000,
    paid: true,
    paidDate: '2026-05-21',
    method: 'Zelle',
    notes: '1st session',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-kade-kean-2026-05-22-01',
    start: '2026-05-22T00:00:00',
    end: '2026-05-22T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['kade-kean'],
    location: '',
    focus: '',
    amountCents: 10000,
    paid: true,
    paidDate: '2026-05-22',
    method: 'Zelle',
    notes: '2nd session - Before Open Room Friday',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-kade-kean-2026-05-25-01',
    start: '2026-05-25T00:00:00',
    end: '2026-05-25T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['kade-kean'],
    location: '',
    focus: '',
    amountCents: 20000,
    paid: true,
    paidDate: '2026-05-25',
    method: 'Zelle',
    notes: '3rd session',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-05-25-01',
    start: '2026-05-25T09:00:00',
    end: '2026-05-25T10:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'Garage 9am',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-kade-kean-2026-05-26-01',
    start: '2026-05-26T00:00:00',
    end: '2026-05-26T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['kade-kean'],
    location: '',
    focus: '',
    amountCents: 20000,
    paid: true,
    paidDate: '2026-05-26',
    method: 'Zelle',
    notes: '4th session',
    status: 'completed',
    sessionsUsed: 0,
  },
  {
    id: 's-paulie-varela-2026-05-26-01',
    start: '2026-05-26T08:31:00',
    end: '2026-05-26T10:01:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'Garage 8:31am',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-kade-kean-2026-05-27-01',
    start: '2026-05-27T00:00:00',
    end: '2026-05-27T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['kade-kean'],
    location: '',
    focus: '',
    amountCents: 20000,
    paid: true,
    paidDate: '2026-05-27',
    method: 'Zelle',
    notes: '5th session',
    status: 'completed',
    sessionsUsed: 0,
  },
  {
    id: 's-paulie-varela-2026-05-27-01',
    start: '2026-05-27T05:00:00',
    end: '2026-05-27T06:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'Garage 5am',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-05-28-01',
    start: '2026-05-28T07:30:00',
    end: '2026-05-28T09:00:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Riverside Submission',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'Riverside Submission 7:30am',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-gage-kotaro-2026-06-01-01',
    start: '2026-06-01T00:00:00',
    end: '2026-06-01T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['gage-kotaro'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Zelle',
    notes: '1st session',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-levi-prado-2026-06-01-01',
    start: '2026-06-01T00:00:00',
    end: '2026-06-01T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['levi-prado'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Zelle',
    notes: '1st session',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-02-01',
    start: '2026-06-02T09:00:00',
    end: '2026-06-02T12:00:00',
    minutes: 180,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'Tuesday garage 9am-12 _ NO ZACH',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-03-01',
    start: '2026-06-03T08:00:00',
    end: '2026-06-03T10:00:00',
    minutes: 120,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'wed. 8-10am',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-04-01',
    start: '2026-06-04T00:00:00',
    end: '2026-06-04T01:00:00',
    minutes: 60,
    kind: 'private',
    offeringId: 'private',
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'MORNING GARAGE',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-08-01',
    start: '2026-06-08T00:00:00',
    end: '2026-06-08T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Riverside Submission',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '1ST AT RIV SUB SIDE',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-09-01',
    start: '2026-06-09T00:00:00',
    end: '2026-06-09T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'SMALL GROUP - 1ST IN OFFICE SIDE',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-09-02',
    start: '2026-06-09T18:00:00',
    end: '2026-06-09T19:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '6PM LIFT BEFORE DEEP WATERS PRACTICE',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-10-01',
    start: '2026-06-10T00:00:00',
    end: '2026-06-10T01:30:00',
    minutes: 90,
    kind: 'workout',
    offeringId: 'workout',
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'DOM BOZNIC, REMY , PAULIE, ZACH, TOE, ISAAC, ROSIE OUTSIDE FARMERS CARRIES',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-10-02',
    start: '2026-06-10T18:00:00',
    end: '2026-06-10T19:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '6PM DRILL TACTICS',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-11-01',
    start: '2026-06-11T00:00:00',
    end: '2026-06-11T01:30:00',
    minutes: 90,
    kind: 'workout',
    offeringId: 'workout',
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-11-02',
    start: '2026-06-11T00:00:00',
    end: '2026-06-11T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-12-01',
    start: '2026-06-12T05:00:00',
    end: '2026-06-12T06:30:00',
    minutes: 90,
    kind: 'workout',
    offeringId: 'workout',
    athleteIds: ['paulie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: '5AM FRIDAY GARAGE W PAULIE FULL BODY LIFT',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-13-01',
    start: '2026-06-13T00:00:00',
    end: '2026-06-13T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: 'Beach',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'BEACH DAY WORKOUT',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-paulie-varela-2026-06-14-01',
    start: '2026-06-14T00:00:00',
    end: '2026-06-14T01:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['paulie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: 'Cash',
    notes: 'ANI + MATCH DAY',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-17-01',
    start: '2026-06-17T05:15:00',
    end: '2026-06-17T06:45:00',
    minutes: 90,
    kind: 'workout',
    offeringId: 'workout',
    athleteIds: ['rosie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: 300000,
    paid: true,
    paidDate: '2026-06-17',
    method: 'Cash',
    notes: '5:15:00 AM - Garage Home full body',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-17-02',
    start: '2026-06-17T18:00:00',
    end: '2026-06-17T19:00:00',
    minutes: 60,
    kind: 'group',
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '6PM - DEEP WATERS RTC PRE WORKKOUT DRILL',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-18-01',
    start: '2026-06-18T06:00:00',
    end: '2026-06-18T07:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: 'Home Garage',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '6AM HOME GARAGE WORKOUT',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-18-02',
    start: '2026-06-18T18:01:00',
    end: '2026-06-18T19:31:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '6:01PM PREWOROKOUT DRILL',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-19-01',
    start: '2026-06-19T18:01:00',
    end: '2026-06-19T19:31:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '6:01PM, PREWORKOUT DRILL',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-24-01',
    start: '2026-06-24T06:00:00',
    end: '2026-06-24T07:30:00',
    minutes: 90,
    kind: 'group',
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '6am morning w jadyn + kAYLA',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-29-01',
    start: '2026-06-29T00:00:00',
    end: '2026-06-29T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-06-30-01',
    start: '2026-06-30T00:00:00',
    end: '2026-06-30T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'completed',
    sessionsUsed: 1,
  },
  {
    id: 's-rosie-varela-2026-07-01-01',
    start: '2026-07-01T00:00:00',
    end: '2026-07-01T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'scheduled',
    sessionsUsed: 0,
  },
  {
    id: 's-rosie-varela-2026-07-02-01',
    start: '2026-07-02T00:00:00',
    end: '2026-07-02T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'scheduled',
    sessionsUsed: 0,
  },
  {
    id: 's-rosie-varela-2026-07-03-01',
    start: '2026-07-03T00:00:00',
    end: '2026-07-03T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'scheduled',
    sessionsUsed: 0,
  },
  {
    id: 's-rosie-varela-2026-07-04-01',
    start: '2026-07-04T00:00:00',
    end: '2026-07-04T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'scheduled',
    sessionsUsed: 0,
  },
  {
    id: 's-rosie-varela-2026-07-05-01',
    start: '2026-07-05T00:00:00',
    end: '2026-07-05T01:00:00',
    minutes: 60,
    kind: null,
    offeringId: null,
    athleteIds: ['rosie-varela'],
    location: '',
    focus: '',
    amountCents: null,
    paid: false,
    paidDate: null,
    method: null,
    notes: '',
    status: 'scheduled',
    sessionsUsed: 0,
  },
];


/**
 * Provenance for every session: his verbatim cell contents, how each one
 * resolved, and which values were inferred. Read this before trusting a start
 * time or a duration.
 */
export const HISTORY_SESSION_META: Readonly<Record<SessionId, HistorySessionMeta>> = {
  's-callum-barkenhagen-2026-05-19-01': {
    sourceSheet: 'Callum Barkenhagen',
    sourceRow: 38,
    clientId: 'callum-barkenhagen',
    packageTypeId: 'other',
    rawPackageType: 'Other',
    packageMatch: 'exact',
    trainingTypeId: 'partner',
    rawTrainingType: '1-on-1 w Grey Oshiro (partner)',
    trainingMatch: 'alias',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 100000,
    owedCents: 0,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Norco / Future Champions "CHAMP CLUB"',
  },
  's-gage-kotaro-2026-06-01-01': {
    sourceSheet: 'GAGE KOTARO',
    sourceRow: 40,
    clientId: 'gage-kotaro',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: 0,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-kade-kean-2026-05-21-01': {
    sourceSheet: 'Kade Kean',
    sourceRow: 33,
    clientId: 'kade-kean',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 20000,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-kade-kean-2026-05-22-01': {
    sourceSheet: 'Kade Kean',
    sourceRow: 34,
    clientId: 'kade-kean',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 10000,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-kade-kean-2026-05-25-01': {
    sourceSheet: 'Kade Kean',
    sourceRow: 35,
    clientId: 'kade-kean',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 20000,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-kade-kean-2026-05-26-01': {
    sourceSheet: 'Kade Kean',
    sourceRow: 36,
    clientId: 'kade-kean',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 20000,
    owedCents: 20000,
    sessionsUsedRaw: 0,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-kade-kean-2026-05-27-01': {
    sourceSheet: 'Kade Kean',
    sourceRow: 37,
    clientId: 'kade-kean',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: 20000,
    owedCents: 20000,
    sessionsUsedRaw: 0,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-levi-prado-2026-06-01-01': {
    sourceSheet: 'LEVI PRADO',
    sourceRow: 39,
    clientId: 'levi-prado',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: 'zelle',
    rawPaymentMethod: 'Zelle',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: 0,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-11-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 13,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'strength-conditioning',
    rawTrainingType: 'STRENGTH',
    trainingMatch: 'alias',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'CASH',
    paymentMatch: 'exact',
    paidCents: 300000,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-16-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 14,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'tournament',
    rawTrainingType: 'TOURNAMENT',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'CASH',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-17-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 15,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-25-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 16,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-26-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 17,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-27-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 18,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-05-28-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 19,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-02-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 20,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'note-range',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-03-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 21,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'note-range',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-04-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 22,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: '1-on-1',
    rawTrainingType: '1-on-1',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-08-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 23,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-09-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 24,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-09-02': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 25,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-10-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 26,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'strength-conditioning',
    rawTrainingType: 'Strength & Conditioning',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-10-02': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 27,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-11-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 28,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'strength-conditioning',
    rawTrainingType: 'Strength & Conditioning',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-11-02': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 29,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'group-session',
    rawTrainingType: 'Group Session',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-12-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 30,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'strength-conditioning',
    rawTrainingType: 'Strength & Conditioning',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-13-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 31,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-paulie-varela-2026-06-14-01': {
    sourceSheet: 'PAULIE VARELA',
    sourceRow: 32,
    clientId: 'paulie-varela',
    packageTypeId: '20-session-package',
    rawPackageType: '20-Session Package',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'DEEP WATERS RTC / Future Champions "CHAMP CLUB"',
  },
  's-rosie-varela-2026-06-17-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 0,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'strength-conditioning',
    rawTrainingType: 'Strength & Conditioning',
    trainingMatch: 'exact',
    paymentMethodId: 'cash',
    rawPaymentMethod: 'Cash',
    paymentMatch: 'exact',
    paidCents: 300000,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-17-02': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 1,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'drill',
    rawTrainingType: 'DRILL',
    trainingMatch: 'exact',
    paymentMethodId: null,
    rawPaymentMethod: '-',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-18-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 2,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: null,
    rawPaymentMethod: '-',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: 'note-keyword',
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-18-02': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 3,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: null,
    rawPaymentMethod: '-',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-19-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 4,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-24-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 5,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: 'small-group',
    rawTrainingType: 'Small Group',
    trainingMatch: 'exact',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: true,
    durationSource: 'training-type-default',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-29-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 6,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-06-30-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 7,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: 1,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: true,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-07-01-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 8,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: null,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: false,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-07-02-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 9,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: null,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: false,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-07-03-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 10,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: null,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: false,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-07-04-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 11,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: null,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: false,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
  's-rosie-varela-2026-07-05-01': {
    sourceSheet: 'Rosie Varela',
    sourceRow: 12,
    clientId: 'rosie-varela',
    packageTypeId: 'single-session',
    rawPackageType: 'Single Session',
    packageMatch: 'exact',
    trainingTypeId: null,
    rawTrainingType: '',
    trainingMatch: 'blank',
    paymentMethodId: null,
    rawPaymentMethod: '',
    paymentMatch: 'blank',
    paidCents: null,
    owedCents: null,
    sessionsUsedRaw: null,
    startTimeRecorded: false,
    durationSource: 'fallback-60',
    locationSource: null,
    logged: false,
    clubAffiliationRaw: 'Deep Waters RTC',
  },
};


/**
 * One payment per row where he recorded money, sorted by date then id. Rows
 * with `-` or a blank Paid cell produce NO payment — they are unrecorded, not
 * zero.
 */
export const HISTORY_PAYMENTS: readonly Payment[] = [
  {
    id: 'pay-paulie-varela-2026-05-11-01',
    date: '2026-05-11',
    clientId: 'paulie-varela',
    sessionId: 's-paulie-varela-2026-05-11-01',
    offeringId: 'workout',
    category: 'package',
    amountCents: 300000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 300000,
    currency: 'USD',
    method: 'Cash',
    source: 'cash',
    status: 'paid',
    description: '20-Session Package · Strength & Conditioning',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-callum-barkenhagen-2026-05-19-01',
    date: '2026-05-19',
    clientId: 'callum-barkenhagen',
    sessionId: 's-callum-barkenhagen-2026-05-19-01',
    offeringId: 'partner',
    category: 'partner',
    amountCents: 100000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 100000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Other · Partner Session',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-kade-kean-2026-05-21-01',
    date: '2026-05-21',
    clientId: 'kade-kean',
    sessionId: 's-kade-kean-2026-05-21-01',
    offeringId: 'private',
    category: 'private',
    amountCents: 20000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 20000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Single Session · 1-on-1',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-kade-kean-2026-05-22-01',
    date: '2026-05-22',
    clientId: 'kade-kean',
    sessionId: 's-kade-kean-2026-05-22-01',
    offeringId: 'private',
    category: 'private',
    amountCents: 10000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 10000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Single Session · 1-on-1',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-kade-kean-2026-05-25-01',
    date: '2026-05-25',
    clientId: 'kade-kean',
    sessionId: 's-kade-kean-2026-05-25-01',
    offeringId: 'private',
    category: 'private',
    amountCents: 20000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 20000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Single Session · 1-on-1',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-kade-kean-2026-05-26-01',
    date: '2026-05-26',
    clientId: 'kade-kean',
    sessionId: 's-kade-kean-2026-05-26-01',
    offeringId: 'private',
    category: 'private',
    amountCents: 20000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 20000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Single Session · 1-on-1',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-kade-kean-2026-05-27-01',
    date: '2026-05-27',
    clientId: 'kade-kean',
    sessionId: 's-kade-kean-2026-05-27-01',
    offeringId: 'private',
    category: 'private',
    amountCents: 20000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 20000,
    currency: 'USD',
    method: 'Zelle',
    source: 'zelle',
    status: 'paid',
    description: 'Single Session · 1-on-1',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
  {
    id: 'pay-rosie-varela-2026-06-17-01',
    date: '2026-06-17',
    clientId: 'rosie-varela',
    sessionId: 's-rosie-varela-2026-06-17-01',
    offeringId: 'workout',
    category: 'workout',
    amountCents: 300000,
    refundedCents: 0,
    feeCents: 0,
    netCents: 300000,
    currency: 'USD',
    method: 'Cash',
    source: 'cash',
    status: 'paid',
    description: 'Single Session · Strength & Conditioning',
    shopifyOrderId: null,
    shopifyOrderName: null,
  },
];


/**
 * His own May 2026 Dashboard, transcribed verbatim into cents. NOTHING here is
 * derived from the session rows — this is what his spreadsheet claims, carried
 * so a screen can show his number next to the imported one. Note that
 * `byStream` sums to $15,874.50 while `incomeCents` says $11,075.
 */
export const HISTORY_MAY_DASHBOARD: DashboardMonth = {
  month: '2026-05',
  incomeCents: 1107500,
  expensesCents: 317000,
  netCents: 790500,
  outstandingCents: 0,
  activeClients: 5,
  coachPayCents: 100000,
  byStream: [
    {
      incomeStreamId: 'personal-training',
      cents: 420000,
    },
    {
      incomeStreamId: 'deep-waters',
      cents: 700000,
    },
    {
      incomeStreamId: 'future-champions',
      cents: 50000,
    },
    {
      incomeStreamId: 'cbu-scholarship-stipend',
      cents: 217450,
    },
    {
      incomeStreamId: 'merch-deep-waters-singlets',
      cents: 200000,
    },
  ],
};


/**
 * Where the imported book and his own reporting disagree. Render these; do not
 * resolve them. Only a line with `resolved: true` actually ties out.
 */
export const HISTORY_RECONCILIATION: readonly ReconciliationLine[] = [
  {
    id: 'may-vs-personal-training',
    label: 'May session log vs Dashboard "Personal Training"',
    importedCents: 490000,
    dashboardCents: 420000,
    deltaCents: 70000,
    note: 'The session log is the only source for personal-training revenue, so these should agree. They do not.',
    resolved: false,
  },
  {
    id: 'may-vs-total-income',
    label: 'May session log vs Dashboard total income',
    importedCents: 490000,
    dashboardCents: 1107500,
    deltaCents: -617500,
    note: 'Expected to differ: club dues, camps, the CBU stipend and merch are never entered as session rows. The gap is not evidence of an error.',
    resolved: false,
  },
  {
    id: 'dashboard-internal',
    label: 'Dashboard income vs Dashboard income-by-stream',
    importedCents: 1587450,
    dashboardCents: 1107500,
    deltaCents: 479950,
    note: 'His own sheet disagrees with itself. Both figures are carried; neither has been picked as the truth.',
    resolved: false,
  },
  {
    id: 'outstanding',
    label: 'Owed column vs Dashboard outstanding',
    importedCents: 40000,
    dashboardCents: 0,
    deltaCents: 40000,
    note: 'His Owed column carries a balance the Dashboard reports as zero.',
    resolved: false,
  },
  {
    id: 'active-clients',
    label: 'Client tabs vs Dashboard active clients',
    importedCents: null,
    dashboardCents: null,
    deltaCents: null,
    note: '6 real client tabs in the book; the Dashboard says 5 active. 5 import as Active and 1 as Owes Balance, which may be the whole explanation — confirm with Jesse.',
    resolved: false,
  },
];


/** What the importer did, in full. Drives the data-provenance panel. */
export const HISTORY_IMPORT_REPORT: ImportReport = {
  sourceRowCount: 45,
  importedRowCount: 41,
  clientCount: 6,
  paymentCount: 8,
  paymentTotalCents: 790000,
  paymentTotalByMonth: {
    '2026-05': 490000,
    '2026-06': 300000,
  },
  outstandingCents: 40000,
  dateRange: {
    first: '2026-05-11',
    last: '2026-07-05',
  },
  perClient: [
    {
      clientId: 'callum-barkenhagen',
      name: 'Callum Barkenhagen',
      sessions: 1,
      logged: 1,
      payments: 1,
      paidCents: 100000,
      owedCents: 0,
    },
    {
      clientId: 'gage-kotaro',
      name: 'Gage Kotaro',
      sessions: 1,
      logged: 1,
      payments: 0,
      paidCents: 0,
      owedCents: 0,
    },
    {
      clientId: 'kade-kean',
      name: 'Kade Kean',
      sessions: 5,
      logged: 5,
      payments: 5,
      paidCents: 90000,
      owedCents: 40000,
    },
    {
      clientId: 'levi-prado',
      name: 'Levi Prado',
      sessions: 1,
      logged: 1,
      payments: 0,
      paidCents: 0,
      owedCents: 0,
    },
    {
      clientId: 'paulie-varela',
      name: 'Paulie Varela',
      sessions: 20,
      logged: 20,
      payments: 1,
      paidCents: 300000,
      owedCents: 0,
    },
    {
      clientId: 'rosie-varela',
      name: 'Rosie Varela',
      sessions: 13,
      logged: 8,
      payments: 1,
      paidCents: 300000,
      owedCents: 0,
    },
  ],
  skipped: [
    {
      sourceRow: 41,
      sheet: 'Sheet1',
      reason: 'Empty workbook template tab, not a client.',
    },
    {
      sourceRow: 42,
      sheet: 'Sheet2',
      reason: 'Empty workbook template tab, not a client.',
    },
    {
      sourceRow: 43,
      sheet: 'Sheet3',
      reason: 'Empty workbook template tab, not a client.',
    },
    {
      sourceRow: 44,
      sheet: 'Sheet4',
      reason: 'Empty workbook template tab, not a client.',
    },
  ],
  aliased: [
    {
      vocabulary: 'paymentMethod',
      raw: 'CASH',
      canonicalId: 'cash',
      canonicalLabel: 'Cash',
      match: 'exact',
    },
    {
      vocabulary: 'trainingType',
      raw: '1-on-1 w Grey Oshiro (partner)',
      canonicalId: 'partner',
      canonicalLabel: 'Partner Session',
      match: 'alias',
    },
    {
      vocabulary: 'trainingType',
      raw: 'DRILL',
      canonicalId: 'drill',
      canonicalLabel: 'Drill',
      match: 'exact',
    },
    {
      vocabulary: 'trainingType',
      raw: 'STRENGTH',
      canonicalId: 'strength-conditioning',
      canonicalLabel: 'Strength & Conditioning',
      match: 'alias',
    },
    {
      vocabulary: 'trainingType',
      raw: 'TOURNAMENT',
      canonicalId: 'tournament',
      canonicalLabel: 'Tournament',
      match: 'exact',
    },
  ],
  invented: [
    {
      vocabulary: 'trainingType',
      id: 'partner',
      label: 'Partner Session',
      reason: 'His book contains "1-on-1 w Grey Oshiro (partner)". A two-athlete session is not a 1-on-1 and is priced as a shared rate.',
    },
    {
      vocabulary: 'trainingType',
      id: 'drill',
      label: 'Drill',
      reason: 'His book contains "DRILL". A drilling block is not a "Small Group" and not "Club Practice".',
    },
    {
      vocabulary: 'trainingType',
      id: 'tournament',
      label: 'Tournament',
      reason: 'His book contains "TOURNAMENT". Cornering at an event is coaching time, not mat instruction.',
    },
    {
      vocabulary: 'incomeStream',
      id: 'cbu-scholarship-stipend',
      label: 'CBU SCHOLARSHIP STIPEND',
      reason: 'On his Dashboard, missing from the Lists sheet.',
    },
    {
      vocabulary: 'incomeStream',
      id: 'merch-deep-waters-singlets',
      label: 'MERCH / DEEP WATERS SINGLETS',
      reason: 'On his Dashboard, missing from the Lists sheet.',
    },
  ],
  unmapped: [],
  flags: [
    {
      code: 'may-vs-personal-training',
      severity: 'warning',
      message: 'The session log is the only source for personal-training revenue, so these should agree. They do not.',
    },
    {
      code: 'dashboard-internal',
      severity: 'warning',
      message: 'His own sheet disagrees with itself. Both figures are carried; neither has been picked as the truth.',
    },
    {
      code: 'outstanding',
      severity: 'warning',
      message: 'His Owed column carries a balance the Dashboard reports as zero.',
    },
    {
      code: 'active-clients',
      severity: 'info',
      message: '6 real client tabs in the book; the Dashboard says 5 active. 5 import as Active and 1 as Owes Balance, which may be the whole explanation — confirm with Jesse.',
    },
  ],
};


/* ==========================================================================
 * HELPERS
 * ======================================================================== */

/**
 * Narrow a `HistorySession` to the strict `TrainingSession` some components
 * require. You must name the fallbacks, because the book does not know them —
 * that is the point. `fallbackKind` fills a blank Training Type;
 * `fallbackAmountCents` fills a session he never priced.
 */
export function toTrainingSession(
  session: HistorySession,
  fallbackKind: SessionKind,
  fallbackAmountCents: number,
): TrainingSession {
  return {
    ...session,
    kind: session.kind ?? fallbackKind,
    amountCents: session.amountCents ?? fallbackAmountCents,
  };
}

/** All sessions for one client, already in start order. */
export function historySessionsFor(clientId: string): readonly HistorySession[] {
  return HISTORY_SESSIONS.filter((s) => s.athleteIds.includes(clientId));
}

/** All payments for one client, already in date order. */
export function historyPaymentsFor(clientId: string): readonly Payment[] {
  return HISTORY_PAYMENTS.filter((p) => p.clientId === clientId);
}

/** The provenance record behind a session, or `null` if the id is unknown. */
export function historyMetaFor(
  sessionId: SessionId,
): HistorySessionMeta | null {
  return HISTORY_SESSION_META[sessionId] ?? null;
}

/**
 * Payment gross for a month key (`'2026-05'`), in cents. Returns 0 for a month
 * with no recorded payments — which is not the same as a month he did not work.
 */
export function historyGrossForMonth(month: string): number {
  return HISTORY_PAYMENTS.filter((p) => p.date.slice(0, 7) === month).reduce(
    (sum, p) => sum + p.amountCents,
    0,
  );
}

/** Payment categories present in the book, in a stable order. */
export const HISTORY_PAYMENT_CATEGORIES: readonly PaymentCategory[] = [
  ...new Set(HISTORY_PAYMENTS.map((p) => p.category)),
].sort();
